
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wisc_cs_jam_opennwa_OpenNWALibrary */

#ifndef _Included_edu_wisc_cs_jam_opennwa_OpenNWALibrary
#define _Included_edu_wisc_cs_jam_opennwa_OpenNWALibrary
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     edu_wisc_cs_jam_opennwa_OpenNWALibrary
 * Method:    findAcceptedWord
 * Signature: (Ledu/wisc/cs/jam/PolicyControlProduct;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_wisc_cs_jam_opennwa_OpenNWALibrary_findAcceptedWord
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_wisc_cs_jam_opennwa_OpenNWALibrary
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wisc_cs_jam_opennwa_OpenNWALibrary_initialize
  (JNIEnv *, jobject);

/*
 * Class:     edu_wisc_cs_jam_opennwa_OpenNWALibrary
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_wisc_cs_jam_opennwa_OpenNWALibrary_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif

